---
- hosts: aws_server
  remote_user: ubuntu
  sudo: yes
  roles:
    - common
    - nodejs
  tasks:
    - name: Install forever
      become: yes
      become_method: sudo
      shell: npm install -g forever
    
    - name: make sure all port stopped
      become: yes
      become_method: sudo
      shell: forever stopall
    
    - name: Creates .ssh directory for root
      sudo: yes
      file: path=/root/.ssh state=directory

    - name: Upload the private key used for Github cloning
      sudo: yes
      copy: src=../../keys/key4m3github.pem dest=/root/.ssh/github

    - name: Correct SSH deploy key permissions
      sudo: yes
      file: dest=/root/.ssh/github mode=0600

    - name: Deploy site files from Github repository
      sudo: yes
      git: repo=git@github.ncsu.edu:DevOps-Milestones/M3-simpleApp.git dest=/home/ubuntu/M3-simpleApp key_file=/root/.ssh/github accept_hostkey=yes force=yes
    
    - name: install packages for M3-simpleApp
      sudo: yes
      shell: cd /home/ubuntu/M3-simpleApp && npm install
    
    - name: start stable server at 3000
      sudo: yes
      shell: cd /home/ubuntu/M3-simpleApp && forever start stable_inst.js 3000
      
    - name: start canary server at 3001
      sudo: yes
      shell: cd /home/ubuntu/M3-simpleApp && forever start canary.js 3001

    - name: start monitoring
      shell: cd /home/ubuntu/M3-simpleApp && forever start monitoring.js
