---
- hosts: aws_server
  remote_user: ubuntu

  tasks:
    - name: install Redis server
      become: yes
      become_method: sudo
      apt: name=redis-server state=latest update_cache=yes

    - name: start redis server
      become: yes
      become_method: sudo
      command: redis-server --daemonize yes

    - name: check if Redis is running
      become: yes
      become_method: sudo
      service: name=redis-server state=started

    - name: enable redis-server to survive reboot
      become: yes
      become_method: sudo
      service: name=redis-server enabled=yes

    - name: flush all redis
      shell: echo 'flushall' | redis-cli

    - name: init the flag
      shell: echo 'set flag 11011'|redis-cli
    
    - name: init ip set
      shell: echo 'lpush proxy 54.164.22.224'| redis-cli