---
- hosts: aws_server
  remote_user: ubuntu

  tasks:
    - name: install Redis server
      become: yes
      become_method: sudo
      apt: name=redis-server state=latest update_cache=yes

    - name: start redis server
      become: yes
      become_method: sudo
      command: redis-server --daemonize yes

    - name: check if Redis is running
      become: yes
      become_method: sudo
      service: name=redis-server state=started

    - name: enable redis-server to survive reboot
      become: yes
      become_method: sudo
      service: name=redis-server enabled=yes

    - name: init the flag
      shell: echo 'set flag 11011' | redis-cli

    - name: init alert set
      shell: echo 'set alert 0' | redis-cli

    - name: forever stop all services
      sudo: yes
      shell: forever stopall

    - name: makesure jenkins is running
      sudo: yes
      shell: service jenkins restart

    - name: Creates .ssh directory for root
      sudo: yes
      file: path=/root/.ssh state=directory

    - name: Upload the private key used for Github cloning
      sudo: yes
      copy: src=../keys/key4m3github-master-server dest=/root/.ssh/github

    - name: Correct SSH deploy key permissions
      sudo: yes
      file: dest=/root/.ssh/github mode=0600

    - name: Deploy site files from Github repository
      sudo: yes
      git: repo=git@github.ncsu.edu:DevOps-Milestones/DevOps-M3.git dest=/home/ubuntu/DevOps-M3 key_file=/root/.ssh/github accept_hostkey=yes force=yes
    
    - name: install packages for DevOps-M3 1
      sudo: yes
      shell: cd /home/ubuntu/DevOps-M3/ec2_manager && npm install

    - name: install packages for DevOps-M3 2
      sudo: yes
      shell: cd /home/ubuntu/DevOps-M3/flag_selector && npm install

    - name: install packages for DevOps-M3 3
      sudo: yes
      shell: cd /home/ubuntu/DevOps-M3/load_balancer && npm install

    - name: install packages for DevOps-M3 4
      sudo: yes
      shell: cd /home/ubuntu/DevOps-M3/monitoring && npm install

    - name: load the balancer
      sudo: yes
      shell: cd /home/ubuntu/DevOps-M3/load_balancer && forever start balancer.js

    - name: load the selector
      sudo: yes
      shell: cd /home/ubuntu/DevOps-M3/flag_selector && forever start selector.js

    - name: re-deploy all slavers
      sudo: yes
      shell: cd /home/ubuntu/DevOps-M3/ec2_manager && bash deploy_all_slavers.sh

    - name: start scaling
      sudo: yes
      shell: cd /home/ubuntu/DevOps-M3/ec2_manager && forever start ../monitoring/scaling.js
